/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package anime_list;

import anime_list.controller.AniListController;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        AniListController ac = new AniListController();
        ac.getAniList();
    }
}
